// qslwidgets/src/CommonWidget.tsx
import React from "react";
import {
  Box,
  ThemeProvider,
  ScopedCssBaseline,
  createTheme,
} from "@mui/material";
import {
  ImageLabeler,
  VideoLabeler,
  Labels,
  Config,
  BatchImageLabeler,
  TimestampedLabel,
  MediaIndex,
  Labeler,
  TimeSeriesLabeler,
} from "./react-image-labeler";
import GlobalLabelerContext from "./react-image-labeler/components/GlobalLabelerContext";
import {
  TimeSeriesTarget,
  IndexState,
} from "./react-image-labeler/components/library/types";

interface BaseWidgetState<T, U, V> {
  states: {
    metadata?: { [key: string]: string };
    selected: boolean;
    visible: boolean;
    ignored: boolean;
    labeled: boolean;
    labels: Labels;
  }[];
  urls: V;
  message: string;
  type: T;
  config: Config;
  labels: U;
  action:
    | "next"
    | "prev"
    | "delete"
    | "ignore"
    | "unignore"
    | "save"
    | "label"
    | "index"
    | "";
  preload: string[];
  maxCanvasSize: number;
  maxViewHeight: number;
  idx: number;
  viewState: "transitioning" | "labeling" | "index";
  indexState: IndexState<string>;
  buttons: {
    next: boolean;
    prev: boolean;
    save: boolean;
    config: boolean;
    delete: boolean;
    ignore: boolean;
    unignore: boolean;
  };
  base: {
    serverRoot: string;
    url: string;
  };
  progress: number;
  mode: "light" | "dark";
}

type ImageWidgetState = BaseWidgetState<"image", Labels, string[]>;
type VideoWidgetState = BaseWidgetState<"video", TimestampedLabel[], string[]>;
type TimeVideoState = BaseWidgetState<
  "time-series",
  Labels,
  TimeSeriesTarget[]
>;
type WidgetState = VideoWidgetState | ImageWidgetState | TimeVideoState;

const defaultWidgetState: WidgetState = {
  states: [],
  urls: [],
  type: "image",
  message: "",
  config: { image: [], regions: [] } as Config,
  labels: { image: {}, polygons: [], masks: [], boxes: [] } as Labels,
  action: "",
  preload: [] as string[],
  maxCanvasSize: 512 as number,
  maxViewHeight: 512 as number,
  idx: 0,
  viewState: "labeling",
  indexState: {
    rows: [],
    columns: [],
    rowsPerPage: 5,
    rowCount: 0,
    sortModel: [],
    page: 1,
  },
  buttons: {
    next: true,
    prev: true,
    save: true,
    config: true,
    delete: true,
    ignore: true,
    unignore: true,
  },
  base: {
    serverRoot: "",
    url: "",
  },
  progress: -1,
  mode: "light" as "light" | "dark",
};

interface CommonWidgetProps {
  extract: <V extends keyof WidgetState & string>(
    name: V
  ) => {
    value: WidgetState[V];
    set: (val: WidgetState[V], options?: any) => void;
  };
}

const InnerCommonWidget: React.FC<CommonWidgetProps> = ({ extract }) => {
  const { setToast } = React.useContext(GlobalLabelerContext);
  const config = extract("config");
  const states = extract("states");
  const urls = extract("urls");
  const type = extract("type");
  const labels = extract("labels");
  const action = extract("action");
  const progress = extract("progress");
  const mode = extract("mode");
  const buttons = extract("buttons");
  const preload = extract("preload");
  const maxCanvasSize = extract("maxCanvasSize");
  const viewState = extract("viewState");
  const indexState = extract("indexState");
  const idx = extract("idx");
  const message = extract("message");
  React.useEffect(() => {
    if (message.value !== "") {
      setToast(message.value);
      message.set("");
    }
  }, [message.value, setToast]);
  const common = {
    config: {
      image: config.value?.image || [],
      regions: config.value?.regions || [],
    },
    preload: preload.value,
    options: {
      progress: progress.value,
      maxCanvasSize: maxCanvasSize.value,
      showNavigation: true,
    },
    callbacks: {
      onSave: buttons.value.save
        ? (updated: any) => {
            labels.set(updated);
            action.set("save");
          }
        : undefined,
      onSaveConfig: buttons.value.config ? config.set : undefined,
      onNext: buttons.value.next ? () => action.set("next") : undefined,
      onPrev: buttons.value.prev ? () => action.set("prev") : undefined,
      onDelete: buttons.value.delete ? () => action.set("delete") : undefined,
      onIgnore: buttons.value.ignore ? () => action.set("ignore") : undefined,
      onUnignore: buttons.value.unignore
        ? () => action.set("unignore")
        : undefined,
      onShowIndex: () => action.set("index"),
    },
  };
  // We use the hidden trick below to get around https://github.com/mui/mui-x/issues/4674
  return (
    <ThemeProvider
      theme={createTheme({
        palette: {
          mode: mode.value || "light",
        },
      })}
    >
      <ScopedCssBaseline>
        <Box style={{ padding: 16 }}>
          <Box hidden={viewState.value !== "index"}>
            <MediaIndex
              indexState={indexState.value}
              setIndexState={(newIndexState) => {
                indexState.set(newIndexState);
                action.set("index");
              }}
              visible={viewState.value === "index"}
              rowKey="qslId"
              idx={idx.value}
              label={(newIdx) => {
                idx.set(newIdx);
                action.set("label");
              }}
            />
          </Box>
          {states.value.length === 0 ||
          viewState.value === "index" ? null : states.value.length == 1 ? (
            type.value === "image" ? (
              <ImageLabeler
                {...common}
                labels={(labels.value || {}) as Labels}
                target={
                  viewState.value === "transitioning"
                    ? undefined
                    : (urls.value as string[])[0]
                }
                metadata={
                  viewState.value === "transitioning"
                    ? {}
                    : states.value[0].metadata
                }
              />
            ) : type.value === "video" ? (
              <VideoLabeler
                {...common}
                labels={
                  (Array.isArray(labels.value)
                    ? labels.value
                    : []) as TimestampedLabel[]
                }
                target={(urls.value as string[])[0]}
                metadata={
                  viewState.value === "transitioning"
                    ? {}
                    : states.value[0].metadata
                }
              />
            ) : type.value == "time-series" ? (
              <TimeSeriesLabeler
                {...common}
                labels={(labels.value || {}) as Labels}
                target={
                  viewState.value === "transitioning"
                    ? undefined
                    : (urls.value[0] as TimeSeriesTarget)
                }
                metadata={
                  viewState.value === "transitioning"
                    ? {}
                    : states.value[0].metadata
                }
              />
            ) : null
          ) : (
            <BatchImageLabeler
              {...common}
              labels={(labels.value || {}) as Labels}
              target={urls.value as string[]}
              states={viewState.value === "transitioning" ? [] : states.value}
              setStates={(newStates) => states.set(newStates)}
            />
          )}
        </Box>
      </ScopedCssBaseline>
    </ThemeProvider>
  );
};

const CommonWidget: React.FC<CommonWidgetProps> = (props) => (
  <Labeler maxViewHeight={props.extract("maxViewHeight").value}>
    <InnerCommonWidget {...props} />
  </Labeler>
);

export { CommonWidget, WidgetState, defaultWidgetState };

// qslwidgets/src/CommonWidget.svelte
<script lang="ts">
  import { Extractor, ActionType } from "./types";
  import { toast } from "./components/library/stores";
  import ImageLabeler from "./components/ImageLabeler.svelte";
  import BatchImageLabeler from "./components/BatchImageLabeler.svelte";
  import MediaIndex from "./components/MediaIndex.svelte";
  import VideoLabeler from "./components/VideoLabeler.svelte";
  import TimeSeriesLabeler from "./components/TimeSeriesLabeler.svelte";
  import Labeler from "./components/Labeler.svelte";
  export let extract: Extractor;
  const viewState = extract("viewState");
  const urls = extract("urls");
  const type = extract("type");
  const config = extract("config");
  const labels = extract("labels");
  const maxCanvasSize = extract("maxCanvasSize");
  const buttons = extract("buttons");
  const states = extract("states");
  const progress = extract("progress");
  const mode = extract("mode");
  const action = extract("action");
  const idx = extract("idx");
  const indexState = extract("indexState");
  const createAction = (name: ActionType) => () => action.set(name);
  const message = extract("message");
  message.subscribe((update: string) => {
    if (update) {
      toast.push(update);
      message.set("");
    }
  });
  $: urlStrings = ($urls as any[]).filter((u) => typeof u === "string");
  $: urlObjects = ($urls as any[]).filter((u) => typeof u === "object");
</script>

<Labeler progress={$progress} mode={$mode}
  >{#if $viewState == "labeling" || $viewState == "transitioning"}
    {#if $urls.length == 1}
      {#if $type === "image" && !Array.isArray($labels)}
        <ImageLabeler
          transitioning={$viewState === "transitioning"}
          target={urlStrings[0]}
          bind:config={$config}
          bind:labels={$labels}
          maxCanvasSize={$maxCanvasSize}
          metadata={$states[0].metadata}
          editableConfig={$buttons.config}
          actions={{ ...$buttons, showIndex: true }}
          on:next={createAction("next")}
          on:prev={createAction("prev")}
          on:delete={createAction("delete")}
          on:ignore={createAction("ignore")}
          on:unignore={createAction("unignore")}
          on:save={createAction("save")}
          on:showIndex={createAction("index")}
        />
      {:else if $type == "video" && Array.isArray($labels)}
        <VideoLabeler
          transitioning={$viewState === "transitioning"}
          target={urlStrings[0]}
          bind:config={$config}
          bind:labels={$labels}
          maxCanvasSize={$maxCanvasSize}
          metadata={$states[0].metadata}
          editableConfig={$buttons.config}
          actions={{ ...$buttons, showIndex: true }}
          on:next={createAction("next")}
          on:prev={createAction("prev")}
          on:delete={createAction("delete")}
          on:ignore={createAction("ignore")}
          on:unignore={createAction("unignore")}
          on:save={createAction("save")}
          on:showIndex={createAction("index")}
        />
      {:else if $type == "time-series" && !Array.isArray($labels)}
        <TimeSeriesLabeler
          transitioning={$viewState === "transitioning"}
          target={urlObjects[0]}
          bind:config={$config}
          bind:labels={$labels}
          editableConfig={$buttons.config}
          actions={{ ...$buttons, showIndex: true }}
          on:next={createAction("next")}
          on:prev={createAction("prev")}
          on:delete={createAction("delete")}
          on:ignore={createAction("ignore")}
          on:unignore={createAction("unignore")}
          on:save={createAction("save")}
          on:showIndex={createAction("index")}
        />
      {:else}
        <div />
      {/if}
    {:else if !Array.isArray($labels)}
      <BatchImageLabeler
        transitioning={$viewState === "transitioning"}
        targets={urlStrings}
        bind:states={$states}
        bind:config={$config}
        bind:labels={$labels}
        editableConfig={$buttons.config}
        actions={{ ...$buttons, showIndex: true }}
        on:next={createAction("next")}
        on:prev={createAction("prev")}
        on:delete={createAction("delete")}
        on:ignore={createAction("ignore")}
        on:unignore={createAction("unignore")}
        on:save={createAction("save")}
        on:showIndex={createAction("index")}
      />
    {/if}
  {:else if $viewState == "index"}
    <MediaIndex
      bind:indexState={$indexState}
      bind:idx={$idx}
      on:label={createAction("label")}
      on:sort={createAction("index")}
    />
  {:else}
    <p>Unexpected view state requested.</p>
    >
  {/if}</Labeler
>
