// qslwidgets/src/components/ControlMenu.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import type {
    Config,
    DraftState,
    LabelConfig,
    LabelData,
    ControlMenuActions,
  } from "../library/types";
  import { shortcutify, focus } from "../library/common";
  import LabelPanel from "./LabelPanel.svelte";
  import ButtonGroup from "./ButtonGroup.svelte";
  import ConfigEditor from "./ConfigEditor.svelte";
  import RangeSlider from "./RangeSlider.svelte";
  import FocusIndicator from "./FocusIndicator.svelte";
  import ClickTarget from "./ClickTarget.svelte";
  export let actions: ControlMenuActions,
    editableConfig: boolean,
    config: Config,
    disabled: boolean,
    navigation: boolean,
    draft: DraftState,
    layout: "horizontal" | "vertical" = "vertical",
    regions: boolean = true;
  const dispatcher = createEventDispatcher();
  $: action = (event: { detail: { name: string } }) =>
    dispatcher(event.detail.name);
  let container: HTMLDivElement;
  $: level = draft.drawing.active
    ? "regions"
    : ("image" as "image" | "regions");
  $: state = {
    labels: draft.drawing.active?.region?.labels || draft.labels.image,
    config: shortcutify(config[level] || []),
  };
  $: valid =
    state.config
      .filter((c) => c.required)
      .every((c) => state.labels[c.name]?.length) &&
    (level === "image" ||
      draft.drawing.mode !== "boxes" ||
      (draft.drawing.active?.region.pt1 && draft.drawing.active?.region.pt2));
  let configEditorOptions = {
    open: false,
    existing: undefined,
  } as {
    open: boolean;
    existing?: { config: LabelConfig; level: "image" | "regions" };
  };
  const saveConfig = (event: {
    detail: { config: LabelConfig; level: "image" | "regions" };
  }) => {
    const level = event.detail.level;
    const levelConfig = config[level] || [];
    const index = levelConfig.findIndex(
      (c) => c.name === event.detail.config.name
    );
    const insert = index > -1 ? index : levelConfig.length;
    config = {
      ...config,
      [level]: levelConfig
        .slice(0, insert)
        .concat([event.detail.config])
        .concat(levelConfig.slice(insert + 1)),
    };
  };
  const save = (event: { detail: { labels: LabelData } }) => {
    dispatcher("change");
    if (draft.drawing.active) {
      draft = {
        ...draft,
        dirty: true,
        drawing: {
          ...draft.drawing,
          active: {
            ...draft.drawing.active,
            region: {
              ...(draft.drawing.active.region as any),
              labels: event.detail.labels,
            },
          },
        },
      };
    } else {
      draft = {
        ...draft,
        dirty: true,
        labels: {
          ...draft.labels,
          image: event.detail.labels,
        },
      };
    }
  };
  $: ensureMaskMode = () => {
    if (!draft.drawing.active && draft.drawing.mode !== "masks") {
      draft = { ...draft, drawing: { ...draft.drawing, mode: "masks" } } as any;
    }
  };
  // Every time the layout changes, re-focus.
  //$: layout, focus(container);
  // On initial menu creation, re-focus.
  onMount(() => focus(container));
</script>

<div class="control-menu {layout}" bind:this={container}>
  <ClickTarget />
  <LabelPanel
    config={state.config}
    labels={state.labels}
    {editableConfig}
    {disabled}
    on:change={save}
    on:editConfig={(event) => {
      const config = state.config.find((c) => c.name == event.detail.name);
      if (config) {
        configEditorOptions = {
          ...configEditorOptions,
          open: true,
          existing: {
            config,
            level,
          },
        };
      }
    }}
  />
  <hr />
  {#if regions && config.regions && config.regions.length > 0}
    <div class="drawing-configuration">
      <div class="drawing-mode">
        <LabelPanel
          editableConfig={false}
          on:change={(event) =>
            (draft = {
              ...draft,
              drawing: {
                ...draft.drawing,
                mode: event.detail.labels.drawingMode[0],
              },
            })}
          disabled={!!draft.drawing.active || disabled}
          labels={{ drawingMode: [draft.drawing.mode] }}
          config={[
            {
              hiderequired: true,
              required: true,
              name: "drawingMode",
              displayName: "Drawing Mode",
              options: [
                { name: "boxes", displayName: "Boxes" },
                { name: "polygons", displayName: "Polygon" },
                { name: "masks", displayName: "Mask" },
              ],
              multiple: false,
              freeform: false,
              layout: "row",
            },
          ]}
        />
      </div>
      <div class="size-threshold">
        <RangeSlider
          name="Cursor Size"
          bind:value={draft.drawing.radius}
          on:change={ensureMaskMode}
          min={1}
          max={50}
          disabled={draft.drawing.active && draft.drawing.mode !== "masks"}
          aria-label="segmentation mask labeling radius"
        />
      </div>
      <div class="flood-threshold">
        <RangeSlider
          name="Flood Fill"
          bind:value={draft.drawing.threshold}
          on:change={ensureMaskMode}
          min={-1}
          step={1}
          marks={[{ value: -1, label: "Off" }].concat(
            new Array(11)
              .fill(undefined)
              .map((v, i) => ({ value: i, label: i.toString() }))
          )}
          disabled={draft.drawing.active && draft.drawing.mode !== "masks"}
          max={10}
          aria-label="segmentation mask flood threshold"
        />
      </div>
    </div>
  {/if}
  <div class="controls">
    <div class="control-group">
      {#if draft.drawing.active}
        <ButtonGroup
          on:click={({ detail: { name } }) => {
            if (name !== "save-region" && name !== "delete-region") {
              dispatcher(name);
              return;
            }
            dispatcher("change");
            draft = {
              ...draft,
              dirty: true,
              labels: {
                ...draft.labels,
                [draft.drawing.mode]: (name === "save-region" &&
                draft.drawing.active
                  ? [draft.drawing.active.region]
                  : []
                ).concat(draft.labels[draft.drawing.mode]),
              },
              drawing: {
                ...draft.drawing,
                active: undefined,
              },
            };
          }}
          configs={[
            {
              text: draft.drawing.active.region.readonly
                ? "Deselect"
                : "Finish",
              event: "save-region",
              disabled: !valid,
              tooltip: valid
                ? "Finish labeling region"
                : "Please fill all required fields.",
              class: "finish-region",
              shortcuts: [{ key: "Enter" }],
            },
            {
              text: "Delete",
              shortcuts: [{ key: "Delete" }, { key: "Backspace" }],
              event: "delete-region",
              tooltip: "Delete this region.",
              disabled: disabled,
            },
            {
              text: "Undo",
              event: "undo",
              tooltip: "Undo last operation",
              hidden: !actions.undo,
              disabled,
              shortcuts: [{ key: "z", ctrlKey: true }],
            },
          ]}
        />
      {:else}
        <ButtonGroup
          on:click={action}
          configs={[
            {
              text: "Save",
              event: "save",
              shortcuts: [{ key: "Enter" }],
              tooltip: valid
                ? "Save current labels."
                : "Please fill all required fields.",
              disabled: !actions.save || disabled || !valid,
            },
            {
              text: actions.ignore ? "Ignore" : "Unignore",
              event: actions.ignore ? "ignore" : "unignore",
              disabled,
              hidden: !actions.ignore && !actions.unignore,
              shortcuts: [],
              tooltip: "Ignore this item.",
            },
            {
              text: "Delete",
              event: "delete",
              shortcuts: [{ key: "Backspace" }, { key: "Delete" }],
              tooltip: "Delete labels",
              disabled,
              hidden: !actions.delete,
            },
            {
              text: "Reset",
              event: "reset",
              hidden: !draft.dirty,
              disabled,
              shortcuts: [],
              tooltip: "Reset labels to current saved version.",
            },
            {
              text: "Undo",
              event: "undo",
              hidden: !actions.undo,
              shortcuts: [{ key: "z", ctrlKey: true }],
              tooltip: "Undo the last action",
              disabled,
            },
            {
              text: "Download",
              event: "download",
              hidden: !actions.download,
              shortcuts: [],
              tooltip: "Download this item.",
              disabled,
            },
          ]}
        />
      {/if}
    </div>
    {#if !draft.drawing.active}
      {#if actions.selectAll || actions.selectNone}
        <div class="control-group">
          <ButtonGroup
            on:click={({ detail: { name } }) => dispatcher(name)}
            configs={[
              {
                text: "Select All",
                event: "selectAll",
                disabled: !actions.selectAll || disabled,
                class: "select-all",
                shortcuts: [{ ctrlKey: true, key: "a" }],
                tooltip: "Select All",
                hidden: !actions.selectAll,
              },
              {
                text: "Select None",
                event: "selectNone",
                disabled: !actions.selectNone || disabled,
                hidden: !actions.selectNone,
                shortcuts: [{ ctrlKey: true, shiftKey: true, key: "a" }],
                tooltip: "Select None",
                class: "select-none",
              },
            ]}
          />
        </div>
      {/if}
      {#if actions.prev || actions.next || navigation}
        <div class="control-group">
          <ButtonGroup
            on:click={action}
            configs={[
              {
                text: "Previous",
                event: "prev",
                disabled: disabled || !actions.prev || draft.dirty,
                shortcuts: [{ key: "ArrowLeft" }],
                tooltip: "Go to previous item.",
              },
              {
                text: "Next",
                event: "next",
                disabled: disabled || !actions.next || draft.dirty,
                shortcuts: [{ key: "ArrowRight" }],
                tooltip: "Got to next item.",
              },
            ]}
          />
        </div>
      {/if}
      {#if editableConfig || actions.showIndex}
        <div class="control-group">
          <ButtonGroup
            on:click={(event) => {
              if (event.detail.name == "showIndex") {
                action(event);
              } else {
                configEditorOptions = {
                  ...configEditorOptions,
                  open: true,
                  existing: undefined,
                };
              }
            }}
            configs={[
              {
                text: "Add Type",
                event: "addType",
                tooltip: "Add new label configuration",
                hidden: !editableConfig,
                shortcuts: [],
                disabled,
              },
              {
                text: "View Index",
                event: "showIndex",
                disabled,
                tooltip: "View media index",
                hidden: !actions.showIndex,
                shortcuts: [],
              },
            ]}
          />
        </div>
      {/if}
    {/if}
    <FocusIndicator />
  </div>
</div>

<ConfigEditor
  open={configEditorOptions.open}
  existing={configEditorOptions.existing}
  on:close={() =>
    (configEditorOptions = { ...configEditorOptions, open: false })}
  on:save={saveConfig}
/>

<style>
  .control-menu {
    position: relative;
  }
  hr {
    color: var(--label-color);
    margin: 10px 0 2px 0;
    border-width: 0.5px;
  }
  .controls {
    display: flex;
    column-gap: 10px;
    row-gap: 10px;
    flex-wrap: wrap;
    margin-top: 10px;
  }
  .vertical .controls {
    flex-direction: row;
    align-items: center;
  }

  .horizontal .controls {
    flex-direction: column;
  }
  .control-group {
    display: flex;
    flex-direction: row;
    align-items: center;
    column-gap: 10px;
    flex: 1 0 auto;
  }
  .control-group :global(.button-group-container) {
    flex: 1 0 auto;
  }
  .drawing-configuration {
    display: flex;
    flex-wrap: wrap;
  }
  .vertical .drawing-configuration {
    flex-direction: row;
    align-items: center;
    column-gap: 15px;
  }

  .horizontal .drawing-configuration {
    flex-direction: column;
  }

  .drawing-configuration .drawing-mode {
    flex: 1 0 0;
  }
  .drawing-configuration .size-threshold,
  .drawing-configuration .flood-threshold {
    flex: 1 0 30%;
  }
  @media (max-width: 640px) {
    .control-group {
      flex: 1 1 100%;
    }
  }
</style>

// qslwidgets/src/react-image-labeler/components/ControlMenu.tsx
import React from "react";
import {
  Box,
  Button,
  Stack,
  Divider,
  ButtonGroup,
  FormControlLabel,
  Checkbox,
  Tooltip,
  useTheme,
  styled,
} from "@mui/material";
import {
  KeyboardArrowRight,
  KeyboardArrowLeft,
  List,
  Keyboard,
  Add,
} from "@mui/icons-material";
import RangeSlider from "./RangeSlider";
import LabelPanel from "./LabelPanel";
import ConfigEditor from "./ConfigEditor";
import ClickTarget from "./ClickTarget";
import GlobalLabelerContext from "./GlobalLabelerContext";
import Metadata from "./Metadata";
import { shortcutify } from "./library/utils";
import { useKeyboardEvent, useMediaLarge } from "./library/hooks";
import { simulateClick } from "./library/utils";
import { DraftState, Config } from "./library/types";

interface Callbacks {
  onKeyboardEvent?: (event: KeyboardEvent) => void;
  onSave?: () => void;
  onNext?: () => void;
  onPrev?: () => void;
  onDelete?: () => void;
  onIgnore?: () => void;
  onUnignore?: () => void;
  onSaveConfig?: (config: Config) => void;
  onReset?: () => void;
  onSelectAll?: () => void;
  onSelectNone?: () => void;
  onShowIndex?: () => void;
  onDownload?: () => void;
  onUndo?: () => void;
}

const StyledButton = styled(Button)`
  &.Mui-disabled {
    pointer-events: auto;
  }
`;

const ButtonWithTooltip = React.forwardRef<
  HTMLButtonElement,
  {
    tooltipText?: string;
    disabled: boolean;
    onClick?: () => void;
  } & React.ComponentProps<typeof Button>
>(({ tooltipText, disabled, onClick, ...other }, ref) => {
  const adjustedButtonProps = {
    disabled: disabled,
    component: disabled ? "div" : undefined,
    onClick: disabled ? undefined : onClick,
  };
  return (
    <Tooltip title={tooltipText || ""}>
      <StyledButton ref={ref} {...other} {...adjustedButtonProps} />
    </Tooltip>
  );
});

const ControlMenu: React.FC<{
  config: Config;
  draft: DraftState;
  setDraft: (draft: DraftState) => void;
  callbacks: Callbacks;
  disabled: boolean;
  showNavigation?: boolean;
  allowRegion?: boolean;
  direction: "column" | "row";
}> = ({
  draft,
  disabled,
  callbacks,
  showNavigation,
  setDraft,
  allowRegion = true,
  ...other
}) => {
  const theme = useTheme();
  const refs = Object.fromEntries(
    [
      "next",
      "prev",
      "save",
      "finishRegion",
      "clearRegion",
      "delete",
      "ignore",
      "selectAll",
      "selectNone",
      "undoRegion",
      "undo",
    ].map((key) => [key, React.useRef<HTMLButtonElement>(null)])
  );
  const isLarge = useMediaLarge();
  const computedState = React.useMemo(() => {
    const level = draft.drawing.active ? "regions" : "image";
    const config = {
      image: shortcutify(other.config?.image || []),
      regions: shortcutify(other.config?.regions || []),
    };
    const activeConfig = config[level] || [];
    return {
      level: level as "regions" | "image",
      activeConfig,
      config,
      direction: isLarge ? other.direction : "column",
      allowRegionSelection:
        config?.regions && config.regions.length > 0 && allowRegion,
      disableLabelPanel:
        disabled ||
        (draft.drawing.active !== undefined &&
          draft.drawing.active.region.readonly === true),
      labels: draft.drawing.active
        ? draft.drawing.active.region.labels
        : draft.labels.image,
      editConfig: callbacks?.onSaveConfig
        ? (name: string) =>
            setState({
              configEditorOpen: true,
              index: activeConfig.findIndex((c) => c.name == name),
            })
        : undefined,
    };
  }, [other.config, draft.labels, draft.drawing.active, allowRegion, disabled]);
  const [state, setState] = React.useState({
    configEditorOpen: false,
    index: null as number | null,
  });
  const { setFocus, hasFocus, setToast } =
    React.useContext(GlobalLabelerContext);
  const requiredFieldsFilled = React.useMemo(() => {
    if (draft.drawing.active) {
      return computedState.activeConfig.every(
        (c) =>
          !c.required ||
          (draft.drawing.active!.region.labels[c.name] || []).length > 0
      );
    } else {
      return computedState.activeConfig.every(
        (c) => !c.required || (draft.labels.image[c.name] || []).length > 0
      );
    }
  }, [draft, computedState]);
  const finishRegion = React.useCallback(
    (save) => {
      if (!draft.drawing.active) {
        throw "Called to finish region but no region is selected.";
      }
      setDraft({
        ...draft,
        dirty: true,
        labels: {
          ...draft.labels,
          [draft.drawing.mode]: (save
            ? [draft.drawing.active.region]
            : []
          ).concat(draft.labels[draft.drawing.mode]),
        },
        drawing: {
          ...draft.drawing,
          active: undefined,
        },
      });
    },
    [draft, computedState, setToast, setDraft]
  );
  useKeyboardEvent(
    (event: KeyboardEvent) => {
      if (callbacks?.onKeyboardEvent) {
        callbacks.onKeyboardEvent(event);
      }
      let target: string | null;
      if (event.altKey) {
        return;
      }
      switch (event.key) {
        case "A":
          target = event.ctrlKey && event.shiftKey ? "selectNone" : null;
          break;
        case "a":
          target = event.ctrlKey && !event.shiftKey ? "selectAll" : null;
          break;
        case "z":
          target =
            event.metaKey !== event.ctrlKey
              ? draft.drawing.active
                ? "undoRegion"
                : "undo"
              : null;
          break;
        case "ArrowRight":
          target = event.ctrlKey || event.shiftKey ? null : "next";
          if (draft.dirty && target !== null) {
            setToast(
              "Please save or reset your changes before advancing to next item."
            );
            target = null;
          }
          break;
        case "ArrowLeft":
          target = "prev";
          if (draft.dirty && target !== null) {
            setToast(
              "Please save or reset your changes before returning to previous item."
            );
            target = null;
          }
          break;
        case "Enter":
          target =
            event.ctrlKey || event.shiftKey
              ? null
              : draft.drawing.active
              ? "finishRegion"
              : "save";
          break;
        case "Backspace":
        case "Delete":
          target =
            event.ctrlKey || event.shiftKey
              ? null
              : draft.drawing.active
              ? "clearRegion"
              : "delete";
          break;
        default:
          return;
      }
      if (
        (target == "finishRegion" || target == "save") &&
        !requiredFieldsFilled
      ) {
        setToast("Please fill in all required fields.");
      } else if (target && refs[target].current) {
        simulateClick(refs[target].current).then(setFocus);
        event.preventDefault();
        event.stopPropagation();
      }
    },
    [callbacks, state, draft, refs, setFocus, setToast, requiredFieldsFilled]
  );
  const setLabels = React.useCallback(
    (current) => {
      setDraft({
        ...draft,
        dirty: true,
        labels: draft.drawing.active
          ? draft.labels
          : {
              ...draft.labels,
              image: current,
            },
        drawing: draft.drawing.active
          ? {
              ...draft.drawing,
              active: {
                ...draft.drawing.active,
                region: {
                  ...draft.drawing.active.region,
                  labels: current,
                } as any,
              },
            }
          : draft.drawing,
      });
    },
    [draft, setDraft]
  );
  return (
    <Box>
      <ClickTarget />
      <LabelPanel
        config={computedState.activeConfig}
        disabled={computedState.disableLabelPanel}
        labels={computedState.labels}
        editConfig={computedState.editConfig}
        setLabels={setLabels}
      />
      {draft.drawing && draft.drawing.active?.region.metadata ? (
        <Box sx={{ position: "relative", zIndex: 1 }}>
          <Metadata data={draft.drawing.active.region.metadata} />
        </Box>
      ) : null}
      {Object.keys(
        (draft.drawing.active
          ? computedState.config.regions
          : computedState.config.image) || []
      ).length > 0 ? (
        <Divider sx={{ mb: 3 }} />
      ) : null}
      {computedState.allowRegionSelection ? (
        <Box>
          <Stack alignContent="center" direction={computedState.direction}>
            <Box
              sx={{
                paddingRight: 2,
                borderRight:
                  draft.drawing.mode === "masks"
                    ? `solid 1px ${theme.palette.divider}`
                    : undefined,
              }}
            >
              <LabelPanel
                setLabels={(labels) =>
                  setDraft({
                    ...draft,
                    drawing: {
                      ...draft.drawing,
                      mode: labels.drawingMode[0] as any,
                    },
                  })
                }
                disabled={!!draft.drawing.active || disabled}
                labels={{ drawingMode: [draft.drawing.mode] }}
                config={[
                  {
                    hiderequired: true,
                    required: true,
                    name: "drawingMode",
                    displayName: "Drawing Mode",
                    options: [
                      { name: "boxes", displayName: "Boxes" },
                      { name: "polygons", displayName: "Polygon" },
                      { name: "masks", displayName: "Mask" },
                    ],
                    multiple: false,
                    freeform: false,
                    layout: "row",
                  },
                ]}
              />
            </Box>
            {draft.drawing.mode === "masks" ? (
              <Box
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    computedState.direction == "row"
                      ? `100px 200px 200px`
                      : `100px 200px`,
                  gridTemplateAreas:
                    computedState.direction == "row"
                      ? '"toggle threshold size"'
                      : '"toggle threshold" "size size"',
                  gridTemplateRows: "auto",
                  columnGap: 25,
                }}
              >
                <FormControlLabel
                  style={{ gridArea: "toggle" }}
                  control={
                    <Checkbox
                      checked={draft.drawing.flood}
                      onChange={(event, flood) =>
                        setDraft({
                          ...draft,
                          drawing:
                            draft.drawing.mode === "masks"
                              ? { ...draft.drawing, flood }
                              : draft.drawing,
                        })
                      }
                    />
                  }
                  label={"Flood"}
                />
                <Box style={{ gridArea: "threshold", display: "inline-flex" }}>
                  <RangeSlider
                    name="Flood Threshold"
                    value={draft.drawing.threshold}
                    min={0}
                    disabled={!draft.drawing.flood}
                    max={20}
                    width="100%"
                    aria-label="segmentation mask flood threshold"
                    onValueChange={(value) =>
                      setDraft({
                        ...draft,
                        drawing: {
                          ...draft.drawing,
                          threshold: value as number,
                        },
                      })
                    }
                  />
                </Box>
                <Box style={{ gridArea: "size", display: "inline-flex" }}>
                  <RangeSlider
                    name="Cursor Size"
                    value={draft.drawing.radius}
                    min={1}
                    max={50}
                    width="100%"
                    aria-label="segmentation mask labeling radius"
                    onValueChange={(value) =>
                      setDraft({
                        ...draft,
                        drawing: {
                          ...draft.drawing,
                          radius: value,
                        },
                      })
                    }
                  />
                </Box>
              </Box>
            ) : null}
          </Stack>
          <Divider sx={{ mb: 2, mt: 2 }} />
        </Box>
      ) : null}
      <Stack direction={computedState.direction} spacing={2}>
        {draft.drawing.active ? (
          <ButtonGroup fullWidth size="small" aria-label="region control menu">
            <ButtonWithTooltip
              ref={refs.finishRegion}
              onClick={() => finishRegion(true)}
              startIcon={"\u23CE"}
              disabled={!requiredFieldsFilled}
              className="finish-region"
              tooltipText={
                requiredFieldsFilled
                  ? undefined
                  : "Please fill all required fields."
              }
            >
              {draft.drawing.active.region.readonly ? "Deselect" : "Finish"}
            </ButtonWithTooltip>
            <Button
              startIcon={"\u232B"}
              disabled={draft.drawing.active.region.readonly}
              onClick={() => finishRegion(false)}
              ref={refs.clearRegion}
            >
              Delete
            </Button>
            {callbacks?.onUndo ? (
              <Button
                disabled={disabled}
                onClick={callbacks.onUndo}
                startIcon={"\u2303Z"}
                ref={refs.undoRegion}
              >
                Undo
              </Button>
            ) : null}
          </ButtonGroup>
        ) : (
          <Stack
            direction={computedState.direction}
            spacing={2}
            style={{ width: "100%" }}
          >
            {callbacks?.onSelectAll || callbacks?.onSelectNone ? (
              <ButtonGroup
                fullWidth
                size="small"
                aria-label="selection control menu"
                className="selection-control"
              >
                {callbacks?.onSelectAll ? (
                  <Button
                    disabled={!callbacks?.onSelectAll || disabled}
                    onClick={callbacks?.onSelectAll}
                    startIcon={"\u2303A"}
                    ref={refs.selectAll}
                    className="select-all"
                  >
                    Select All
                  </Button>
                ) : null}
                {callbacks?.onSelectNone ? (
                  <Button
                    disabled={!callbacks?.onSelectNone || disabled}
                    onClick={callbacks?.onSelectNone}
                    startIcon={"\u2303\u21E7A"}
                    ref={refs.selectNone}
                    className="select-none"
                  >
                    Select None
                  </Button>
                ) : null}
              </ButtonGroup>
            ) : null}
            <ButtonGroup fullWidth size="small" aria-label="label control menu">
              <ButtonWithTooltip
                ref={refs.save}
                disabled={
                  !callbacks?.onSave || disabled || !requiredFieldsFilled
                }
                onClick={callbacks?.onSave}
                startIcon={"\u23CE"}
                className="save"
                tooltipText={
                  requiredFieldsFilled
                    ? undefined
                    : "Please fill all required fields."
                }
              >
                Save
              </ButtonWithTooltip>

              {callbacks?.onIgnore || callbacks?.onUnignore ? (
                <Button
                  ref={refs.ignore}
                  disabled={disabled}
                  onClick={callbacks?.onIgnore || callbacks?.onUnignore}
                >
                  {callbacks?.onIgnore ? "Ignore" : "Unignore"}
                </Button>
              ) : null}
              {callbacks?.onDelete ? (
                <Button
                  startIcon={"\u232B"}
                  ref={refs.delete}
                  disabled={disabled}
                  onClick={callbacks.onDelete}
                >
                  Delete
                </Button>
              ) : null}
              {callbacks?.onReset && draft.dirty ? (
                <Button disabled={disabled} onClick={callbacks.onReset}>
                  Reset
                </Button>
              ) : null}
              {callbacks?.onUndo ? (
                <Button
                  disabled={disabled}
                  onClick={callbacks.onUndo}
                  ref={refs.undo}
                  startIcon={"\u2303Z"}
                >
                  Undo
                </Button>
              ) : null}
              {callbacks.onDownload ? (
                <Button onClick={callbacks.onDownload}>Download</Button>
              ) : null}
            </ButtonGroup>
            {callbacks?.onPrev || callbacks?.onNext || showNavigation ? (
              <ButtonGroup
                size="small"
                fullWidth
                aria-label="navigation control menu"
              >
                <Button
                  startIcon={<KeyboardArrowLeft />}
                  ref={refs.prev}
                  disabled={!callbacks?.onPrev || draft.dirty}
                  onClick={callbacks.onPrev}
                >
                  Previous
                </Button>
                <Button
                  startIcon={<KeyboardArrowRight />}
                  ref={refs.next}
                  disabled={!callbacks?.onNext || draft.dirty}
                  onClick={callbacks.onNext}
                >
                  Next
                </Button>
              </ButtonGroup>
            ) : null}
            {callbacks?.onSaveConfig || callbacks?.onShowIndex ? (
              <ButtonGroup
                size="small"
                aria-label="add new configuration menu"
                fullWidth
              >
                {callbacks?.onSaveConfig ? (
                  <Button
                    startIcon={<Add />}
                    className="add-new-label"
                    onClick={() =>
                      setState({ index: null, configEditorOpen: true })
                    }
                  >
                    Add Type
                  </Button>
                ) : null}
                {callbacks?.onShowIndex ? (
                  <Button
                    startIcon={<List />}
                    className="show-data-index"
                    disabled={disabled}
                    onClick={callbacks.onShowIndex}
                  >
                    View Index
                  </Button>
                ) : null}
              </ButtonGroup>
            ) : null}
          </Stack>
        )}
        <Box
          title={
            hasFocus
              ? "Listening for keyboard shortcuts."
              : "Keyboard shortcuts disabled. Click inside the widget to enable."
          }
          onClick={setFocus}
          style={{ zIndex: 1 }}
        >
          <Keyboard
            color={hasFocus ? "primary" : "warning"}
            fontSize={"large"}
          />
        </Box>
      </Stack>
      {callbacks && callbacks.onSaveConfig && state.configEditorOpen ? (
        <ConfigEditor
          allowRegion={allowRegion}
          open={state.configEditorOpen}
          onClose={() => setState({ ...state, configEditorOpen: false })}
          existing={
            state.index !== null
              ? {
                  config: computedState.activeConfig[state.index],
                  level: computedState.level,
                }
              : undefined
          }
          onSave={(newLabelConfig, level) => {
            if (
              state.index === null &&
              (computedState.config[level] || []).find(
                (c) => c.name === newLabelConfig.name
              )
            ) {
              throw "User attempted to add a config with the name of an existing config.";
            }
            const previous = computedState.config[level];
            const index = state.index === null ? previous.length : state.index;
            callbacks.onSaveConfig!({
              ...computedState.config,
              [level]: previous
                .slice(0, index)
                .concat([newLabelConfig])
                .concat(previous.slice(index + 1)),
            });
            setState({ index: null, configEditorOpen: false });
          }}
        />
      ) : null}
    </Box>
  );
};

export default ControlMenu;
