// qslwidgets/src/react-image-labeler/components/LabelPanelEntry.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { LabelConfig } from "./library/types";
  import {
    buildOptions,
    elementIsFocused,
    simulateClick,
    focus,
  } from "./library/utils";
  import Edit from "carbon-icons-svelte/lib/Edit.svelte";
  import { processSelectionChange } from "./library/handlers";
  export let config: LabelConfig,
    disabled: boolean,
    selected: string[] | undefined,
    editableConfig: boolean;
  const dispatcher = createEventDispatcher();
  let freeform = { value: "", dirty: false };
  let element: HTMLElement;
  $: change = (value: string) =>
    dispatcher("change", {
      selected: processSelectionChange(
        value,
        selected,
        config.multiple,
        config.required
      ),
    });
  $: options = buildOptions(selected, config);
  $: keyMap = (
    options
      ? options.reduce((map, o, i) => {
          return o.shortcut ? { ...map, [o.shortcut as string]: i } : map;
        }, {})
      : {}
  ) as { [key: string]: number };
  $: if (!options && !freeform.dirty && config.freeform && selected) {
    // When we're in freeform-only mode (no options),
    // the clean version of the field should contain the
    // current label.
    freeform = { dirty: false, value: selected[0] || "" };
  }
  $: createOptionCallback = (value: string) => () => change(value);
  $: keyboardEffects = {
    keydown: (event: KeyboardEvent) => {
      if (
        !event.ctrlKey &&
        !event.shiftKey &&
        keyMap &&
        keyMap.hasOwnProperty(event.key) &&
        elementIsFocused(element, event.target)
      ) {
        const idx = keyMap[event.key];
        simulateClick(
          element.querySelector(
            `.react-image-labeler-input-target[data-index='${idx}']`
          ) as HTMLElement
        ).then(() => focus(element));
        event.preventDefault();
        event.stopPropagation();
      }
    },
  };
  $: freeformEffects = {
    modify: () => {
      freeform = { ...freeform, dirty: true };
    },
    blur: () => {
      if (!options) {
        change(freeform.value);
        freeform = { ...freeform, dirty: false };
      } else {
        freeform = { value: "", dirty: false };
      }
    },
    submit: (event: Event) => {
      event.preventDefault();
      event.stopPropagation();
      change(freeform.value);
      focus(element);
      freeform = { ...freeform, dirty: false };
    },
  };
</script>

<svelte:window on:keydown={keyboardEffects.keydown} />
<div bind:this={element} class="label-panel-entry">
  <div class="label-panel-entry-title">
    <span>{config.displayName || config.name} </span>
    {#if config.required && !config.hiderequired}
      <span><sup>*</sup></span>
    {/if}
    {#if editableConfig}
      <button class="icon-button" on:click={() => dispatcher("editConfig")}
        ><Edit /></button
      >
    {/if}
  </div>
  <div
    class="label-panel-entry-values"
    style="flex-direction: {config.layout || 'column'};"
  >
    {#if options}
      {#each options as option, optionIndex}
        <label>
          <input
            class="react-image-labeler-input-target"
            data-index={optionIndex}
            type={config.multiple ? "checkbox" : "radio"}
            checked={option.selected}
            on:click={createOptionCallback(option.name)}
            value={option.name}
          />
          {option.label}</label
        >
      {/each}
    {/if}
    {#if config.freeform}
      {#if options || config.freeformtag === "input"}
        <input
          {disabled}
          bind:value={freeform.value}
          on:blur={freeformEffects.blur}
          on:keydown={(event) =>
            event.key === "Enter"
              ? freeformEffects.submit(event)
              : freeformEffects.modify()}
          class="react-image-labeler-input-target"
        />
      {:else}
        <textarea
          {disabled}
          bind:value={freeform.value}
          on:blur={freeformEffects.blur}
          on:keydown={(event) =>
            event.key === "Enter"
              ? freeformEffects.submit(event)
              : freeformEffects.modify()}
          class="react-image-labeler-input-target"
        />
      {/if}
    {/if}
  </div>
</div>

<style>
  .label-panel-entry {
    z-index: 1;
    position: relative;
    display: flex;
    flex-direction: column;
    flex-grow: 1;
  }
  .label-panel-entry-title {
    display: flex;
    align-items: center;
    flex-direction: row;
    column-gap: 5px;
    color: rgb(100, 100, 100);
    margin: 0.5rem 0;
  }
  .label-panel-entry-values {
    display: flex;
    row-gap: 5px;
    flex-basis: 100%;
  }
  .icon-button {
    position: relative;
    border-radius: 50%;
    background-color: transparent;
    width: 2rem;
    height: 2rem;
  }
  .icon-button:active {
    background-color: lightgrey;
  }
  .icon-button :global(svg) {
    position: absolute;
    width: 50%;
    height: 50%;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
  }
  .label-panel-entry-values textarea {
    height: 100%;
    width: 100%;
    box-sizing: border-box;
  }
</style>

// qslwidgets/src/react-image-labeler/components/LabelPanelEntry.tsx
import React from "react";
import {
  Box,
  FormControl,
  FormControlLabel,
  FormLabel,
  FormGroup,
  Checkbox,
  Input,
  IconButton,
  Radio,
  styled,
} from "@mui/material";
import { Edit } from "@mui/icons-material";
import GlobalLabelerContext from "./GlobalLabelerContext";
import { useKeyboardEvent, simulateClick } from "./library/hooks";
import { processSelectionChange } from "./library/handlers";
import { LabelConfig, Option } from "./library/types";

interface LabelPanelEntryProps {
  config: LabelConfig;
  disabled?: boolean;
  selected?: string[];
  setSelected: (name: string, selected: string[]) => void;
  editConfig?: (name: string) => void;
}

const StyledBox = styled(Box)`
  & label.label-panel-entry-option-label {
    margin-bottom: 0;
  }

  & legend.label-panel-entry-label {
    margin-bottom: 0;
    border-bottom: none;
  }

  & .hide-required .MuiFormLabel-asterisk {
    display: none;
  }
`;

const buildOptionsList = (selected: string[] | undefined, options: Option[]) =>
  options.concat(
    selected
      ? selected
          .filter((s) => (options || []).findIndex((o) => o.name === s) == -1)
          .map((s) => {
            return { name: s, shortcut: "" };
          })
      : []
  );

const LabelPanelEntry: React.FC<LabelPanelEntryProps> = ({
  config,
  selected,
  setSelected,
  disabled,
  editConfig,
}) => {
  const availableOptions = React.useMemo(
    () =>
      config.options || config.multiple
        ? buildOptionsList(selected || [], config.options || [])
        : undefined,
    [config.options, selected]
  );
  const ref = React.useRef<HTMLElement>(null);
  const { setFocus } = React.useContext(GlobalLabelerContext);
  const keyIndexMap: { [key: string]: number } = React.useMemo(
    () =>
      availableOptions
        ? availableOptions.reduce((map, o, i) => {
            return o.shortcut ? { ...map, [o.shortcut as string]: i } : map;
          }, {})
        : {},
    [availableOptions]
  );
  const toggleSelected = React.useCallback(
    (o) =>
      setSelected(
        config.name,
        processSelectionChange(o, selected, config.multiple)
      ),
    [selected, config, setSelected]
  );
  useKeyboardEvent(
    (event: KeyboardEvent) => {
      if (
        // Block if a modifier key is used, or if we've disabled shortcuts,
        // or if the keyOptionMap is empty (meaning there are no shortcuts).
        event.ctrlKey ||
        event.shiftKey ||
        !keyIndexMap
      ) {
        return;
      }
      const idx = keyIndexMap[event.key];
      if (idx > -1 && ref.current) {
        const target = ref.current.querySelector(
          `.react-image-labeler-input-target[data-index='${idx}'] input`
        ) as HTMLElement;
        simulateClick(target);
        event.preventDefault();
        event.stopPropagation();
        setFocus();
      }
    },
    [keyIndexMap, ref, setFocus]
  );
  const [state, setState] = React.useState({
    freeform: "",
  });
  React.useEffect(
    () =>
      setState({
        freeform:
          availableOptions || config.multiple || !config.freeform || !selected
            ? ""
            : selected[0] || "",
      }),
    [selected]
  );
  return (
    <StyledBox display="inline">
      <FormControl
        sx={{ ml: 3, mr: 3, mt: 0, mb: 3 }}
        component="fieldset"
        variant="standard"
        className="label-panel-entry"
        disabled={!!disabled}
        name={config.name}
      >
        <FormLabel
          component="legend"
          className={`label-panel-entry-label ${
            config.hiderequired ? "hide-required" : ""
          }`}
          required={config.required}
        >
          {config.displayName || config.name}{" "}
          {editConfig ? (
            <IconButton
              aria-label={`edit ${config.name}`}
              className="edit-label-entry"
              onClick={() => editConfig(config.name)}
            >
              <Edit />
            </IconButton>
          ) : null}
        </FormLabel>
        <FormGroup ref={ref} row={config.layout == "row"}>
          {(availableOptions || []).map((o, i) => {
            const controlProps = {
              checked: !!(selected && selected.indexOf(o.name) > -1),
              onChange: () => toggleSelected(o.name),
              name: o.name,
              className: "react-image-labeler-input-target",
            };
            const label = `${o.displayName || o.name} ${
              o.shortcut ? `(${o.shortcut})` : ""
            }`;
            return (
              <FormControlLabel
                className={"label-panel-entry-option-label"}
                key={i}
                control={
                  config.multiple ? (
                    <Checkbox {...controlProps} data-index={i} />
                  ) : (
                    // Add the onClick so we can de-select radio selections.
                    <Radio
                      {...controlProps}
                      data-index={i}
                      onClick={controlProps.onChange}
                    />
                  )
                }
                color="primary"
                label={label}
              />
            );
          })}
        </FormGroup>
        {config.freeform ? (
          <Input
            value={state.freeform}
            name={`${config.name}-freeform`}
            placeholder={config.multiple ? "Add new option" : undefined}
            onKeyPress={(event) => {
              if (event.key === "Enter") {
                if (config.multiple || availableOptions) {
                  toggleSelected(state.freeform);
                  setState({
                    freeform: "",
                  });
                } else {
                  setFocus();
                }
                event.preventDefault();
              }
            }}
            onChange={(event) => {
              setState({ ...state, freeform: event.target.value });
              if (!config.multiple && !availableOptions) {
                toggleSelected(event.target.value);
              }
              event.preventDefault();
              event.stopPropagation();
            }}
          />
        ) : null}
      </FormControl>
    </StyledBox>
  );
};

export default LabelPanelEntry;
