// qslwidgets/src/components/MediaViewer.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import type { Dimensions, Point, MediaLoadState } from "../library/types";
  import { convertCoordinates } from "../library/geometry";
  import { focus } from "../library/common";
  import RangeSlider from "./RangeSlider.svelte";
  import ClickTarget from "./ClickTarget.svelte";
  import EnhancementControls from "./EnhancementControls.svelte";
  import Spinner from "./Spinner.svelte";
  import * as useGesture from "@use-gesture/vanilla";
  export let size: Dimensions | undefined,
    viewHeight: number = 384,
    loadState: MediaLoadState = "loaded",
    enhancementControls: boolean = true;
  let main: HTMLDivElement;
  let view: HTMLDivElement;
  let mini: HTMLDivElement;
  let viewWidth: number | undefined = undefined;
  let destroy: () => void;
  const cleanup = () => focus(main);
  const defaultBasis = {
    view: {
      width: undefined as number | undefined,
      height: viewHeight as number,
    },
    size: {
      width: undefined as number | undefined,
      height: undefined as number | undefined,
    },
  };
  const minimapSize = 96;

  $: state = {
    basis: defaultBasis,
    minimap: { width: minimapSize, height: minimapSize, scale: 1 },
    x: 0,
    y: 0,
    zoom: 1,
    fit: 1,
    dragging: false,
  };
  $: if (
    size &&
    viewWidth &&
    (viewWidth !== state.basis.view.width ||
      viewHeight !== state.basis.view.height ||
      state.basis.size.width !== size.width ||
      state.basis.size.height !== size.height)
  ) {
    state = (() => {
      const minimapScale = minimapSize / Math.max(size.width, size.height);
      const fit = Math.min(viewHeight / size.height, viewWidth / size.width);
      return {
        ...state,
        x: 0,
        y: 0,
        basis: {
          view: { width: viewWidth, height: viewHeight },
          size,
        },
        minimap: {
          width: size.width * minimapScale,
          height: size.height * minimapScale,
          scale: minimapScale,
        },
        zoom: fit,
        fit,
      };
    })();
  }
  const zoom2span = (zoom: number) =>
    state.basis.view.width && state.basis.size.width && state.basis.size.height
      ? {
          width: Math.min(
            state.basis.view.width / (zoom * state.basis.size.width),
            1
          ),
          height: Math.min(
            state.basis.view.height / (zoom * state.basis.size.height),
            1
          ),
        }
      : { width: 0, height: 0 };
  $: onMinimapClick = (event: MouseEvent) => {
    if (
      !state.basis.view.width ||
      !state.basis.view.height ||
      !state.basis.size.width ||
      !state.basis.size.height
    )
      return;
    const point = convertCoordinates({ x: event.pageX, y: event.pageY }, mini);
    const span = zoom2span(state.zoom);
    state = {
      ...state,
      x: Math.min(Math.max(point.x - span.width / 2, 0), 1 - span.width),
      y: Math.min(Math.max(point.y - span.height / 2, 0), 1 - span.height),
    };
  };
  $: onMediaScroll = (operation: {
    deltaX: number;
    deltaY: number;
    ctrlKey: boolean;
    center?: Point;
  }) => {
    if (!size) {
      return;
    }
    if (!operation.ctrlKey) {
      state = {
        ...state,
        zoom: state.zoom,
        x: Math.max(state.x - operation.deltaX / (state.zoom * size.width), 0),
        y: Math.max(state.y - operation.deltaY / (state.zoom * size.height), 0),
      };
    } else {
      const zoom = Math.max(
        state.zoom - operation.deltaY / (2 * 100),
        10 / Math.min(size.width, size.height)
      );
      const spani = zoom2span(state.zoom);
      const spanf = zoom2span(zoom);
      const center = operation.center || { x: state.x, y: state.y };
      const relative = {
        x: (center.x - state.x) / spani.width,
        y: (center.y - state.y) / spani.height,
      };
      const next = {
        x: Math.max(center.x - relative.x * spanf.width, 0),
        y: Math.max(center.y - relative.y * spanf.height, 0),
      };
      state = {
        ...state,
        ...next,
        zoom,
      };
    }
  };
  onMount(() => {
    const gestures = new useGesture.Gesture(
      main,
      {
        onDragEnd: () => {
          setTimeout(() => (state = { ...state, dragging: false }), 100);
          cleanup();
        },
        onDrag: ({ delta: [deltaX, deltaY] }) => {
          onMediaScroll({
            deltaX,
            deltaY,
            ctrlKey: false,
          });
        },
        onDragStart: () => {
          state = { ...state, dragging: true };
        },
        onWheel: ({
          delta: [deltaX, deltaY],
          ctrlKey,
          event: { pageX, pageY },
        }) => {
          onMediaScroll({
            deltaX: ctrlKey ? deltaX : -deltaX,
            deltaY: ctrlKey ? deltaY : -deltaY,
            ctrlKey,
            center: convertCoordinates(
              {
                x: pageX,
                y: pageY,
              },
              main
            ),
          });
          cleanup();
        },
        onPinch: (event) => {
          if (event.memo && event.memo > 0 && size) {
            onMediaScroll({
              deltaX: 0,
              deltaY: event.memo - event.da[0],
              ctrlKey: true,
              center: convertCoordinates(
                {
                  x: event.origin[0] + window.scrollX,
                  y: event.origin[1] + window.scrollY,
                },
                main
              ),
            });
          }
          cleanup();
          return event.last ? -1 : event.da[0];
        },
      },
      {
        drag: {
          delay: 500,
        },
        wheel: {
          preventDefault: true,
          eventOptions: {
            passive: false,
          },
        },
      }
    );
    const intervalId = setInterval(() => {
      if (viewWidth !== view.clientWidth) {
        viewWidth = view.clientWidth;
      }
    }, 100);
    destroy = () => {
      gestures.destroy();
      clearInterval(intervalId);
    };
  });
  onDestroy(() => destroy());
</script>

<div
  style="--media-viewer-scale: {state.zoom}; --media-viewer-x: {100 *
    state.x}%; --media-viewer-y: {100 *
    state.y}%; --media-viewer-minimap-scale: {state.minimap
    .scale}; --media-viewer-minimap-width: {state.minimap
    .width}; --media-viewer-minimap-height: {state.minimap.height};
    --media-viewer-minimap-limit-width: {Math.min(
    1 - state.x,
    state.basis.view.width && state.basis.size.width
      ? state.basis.view.width / (state.basis.size.width * state.zoom)
      : 0
  ) * 100}%; --media-viewer-minimap-limit-height: {Math.min(
    1 - state.y,
    state.basis.view.height && state.basis.size.height
      ? state.basis.view.height / (state.basis.size.height * state.zoom)
      : 0
  ) * 100}%;
    "
  class="media-viewer {state.dragging ? 'dragging' : ''}"
>
  <div
    bind:this={view}
    class="viewport"
    style="height: {state.basis.view.height}px; width: 100%"
  >
    <ClickTarget />
    <div class="main" bind:this={main}>
      <div class={loadState}>
        <slot name="main" />
      </div>
      {#if loadState === "loaded"}
        <slot name="regions" />
      {/if}
    </div>
    {#if loadState !== "loaded"}
      <div class="spinner">
        <Spinner />
      </div>
    {/if}
  </div>
  <div class="footer">
    <div class="minimap" bind:this={mini}>
      {#if loadState === "loaded"}
        <div class="image">
          <slot name="mini" />
        </div>
        <slot name="regions" />
        <div class="limits" />
        <div class="click-target" on:click={onMinimapClick} />
      {/if}
    </div>
    <div class="controls">
      <slot name="custom-controls" />
      {#if enhancementControls}
        <EnhancementControls>
          <RangeSlider
            name="Zoom"
            disabled={false}
            min={0.1}
            max={10}
            bind:value={state.zoom}
            marks={[
              { value: 1, label: "1" },
              { value: state.fit, label: "Fit" },
            ]}
          />
        </EnhancementControls>
      {:else}
        <RangeSlider
          name="Zoom"
          disabled={false}
          min={0.1}
          max={10}
          bind:value={state.zoom}
          marks={[
            { value: 1, label: "1" },
            { value: state.fit, label: "Fit" },
          ]}
        />
      {/if}
    </div>
  </div>
</div>

<style>
  .media-viewer {
    display: flex;
    flex-direction: column;
    row-gap: 10px;
    z-index: 1;
  }
  .viewport {
    position: relative;
    overflow: hidden;
  }
  .main {
    transform: scale(var(--media-viewer-scale))
      translate(
        calc(-1 * var(--media-viewer-x)),
        calc(-1 * var(--media-viewer-y))
      );
    transform-origin: 0 0;
    position: absolute;
    touch-action: none;
  }
  .main .loading {
    visibility: hidden;
  }
  .footer {
    display: flex;
    flex-direction: row;
    align-items: center;
    column-gap: 10px;
  }
  .controls {
    flex: 100% 0 1;
  }
  .minimap {
    --media-viewer-scale: scale(
      var(--media-viewer-minimap-scale) / var(--media-viewer-scale)
    );
    width: calc(var(--media-viewer-minimap-width) * 1px);
    height: calc(var(--media-viewer-minimap-height) * 1px);
    position: relative;
    box-shadow: 4px 4px 8px rgb(0, 0, 0, 0.5);
    background-color: var(--background-color);
  }
  .minimap .image {
    transform: scale(var(--media-viewer-minimap-scale));
    transform-origin: 0 0;
  }
  .minimap .limits {
    position: absolute;
    border: 1px solid red;
    box-sizing: border-box;
    left: var(--media-viewer-x);
    top: var(--media-viewer-y);
    width: var(--media-viewer-minimap-limit-width);
    height: var(--media-viewer-minimap-limit-height);
  }

  .minimap :global(.mask-cursor) {
    display: none;
  }

  .minimap .click-target {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 2;
  }
  .main :global(img),
  .main :global(video),
  .minimap :global(img),
  .minimap :global(video) {
    pointer-events: none;
    image-rendering: pixelated;
    vertical-align: bottom;
    -webkit-user-drag: none;
    -khtml-user-drag: none;
    -moz-user-drag: none;
    -o-user-drag: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }
  .minimap :global(text) {
    display: none;
  }

  .media-viewer.dragging {
    cursor: grab;
  }
  .spinner > :global(:first-child) {
    --colorInner: var(--color1);
    --colorCenter: var(--color2);
    --colorOuter: var(--color3);
    position: absolute;
    left: 50%;
    top: 50%;
    right: 50%;
    bottom: 50%;
  }
  .main :global(img),
  .main :global(video) {
    filter: var(--image-enhancements-filter);
  }
</style>

// qslwidgets/src/react-image-labeler/components/MediaViewer.tsx
import React from "react";
import { Box, Paper, CircularProgress, styled } from "@mui/material";
import RangeSlider from "./RangeSlider";
import GlobalLabelerContext from "./GlobalLabelerContext";
import ClickTarget from "./ClickTarget";
import { Dimensions, Point, MediaLoadState } from "./library/types";
import { pct2css } from "./library/utils";
import {
  useInterval,
  useMediaEvent,
  convertCoordinates,
} from "./library/hooks";
import { useGesture } from "@use-gesture/react";

const MAP_SIZE = 96;

const MediaViewerBox = styled(Box)`
  & .minimap .mask-cursor {
    display: none;
  }

  & .minimap .box-text {
    visibility: hidden;
  }

  & .viewport img,
  .viewport video {
    vertical-align: bottom;
  }

  & .viewport .loading-placeholder .region {
    visibility: hidden;
  }

  & img,
  & video {
    max-width: none;
    max-height: none;
    image-rendering: pixelated;
    -webkit-user-drag: none;
    -khtml-user-drag: none;
    -moz-user-drag: none;
    -o-user-drag: none;
    user-drag: none;
  }
`;

const MediaViewer: React.FC<
  {
    media: {
      main: React.ReactNode;
      mini: React.ReactNode;
    };
    size?: Dimensions;
    controls?: React.ReactNode;
    loadState: MediaLoadState;
    maxViewHeight?: number;
    cursor?: Point;
    onMouseLeave?: () => void;
  } & React.ComponentProps<"div">
> = ({
  children,
  media,
  size,
  controls,
  loadState,
  onMouseLeave,
  cursor,
  maxViewHeight = 512,
}) => {
  const { setFocus } = React.useContext(GlobalLabelerContext);
  const refs = {
    viewport: React.useRef<HTMLDivElement>(null),
    minimap: React.useRef<HTMLDivElement>(null),
    media: React.useRef<HTMLDivElement>(null),
  };
  const [state, setState] = React.useState({
    zoom: 1.0,
    pos: { x: 0, y: 0 } as Point,
    minimapSize: { width: MAP_SIZE, height: MAP_SIZE },
    zoomInitialized: false,
  });
  const [dragging, setDragging] = React.useState(false);
  const [maxViewWidth, setMaxViewWidth] = React.useState(maxViewHeight);
  React.useEffect(() => {
    if (loadState === "loading") {
      setState({ ...state, pos: { x: 0, y: 0 }, zoomInitialized: false });
    } else if (
      loadState == "loaded" &&
      size &&
      !state.zoomInitialized &&
      maxViewWidth > 0
    ) {
      const minimapScale = MAP_SIZE / Math.max(size.width, size.height);
      setState({
        ...state,
        zoomInitialized: true,
        zoom: Math.min(maxViewWidth / size.width, maxViewHeight / size.height),
        minimapSize: {
          width: minimapScale * size.width,
          height: minimapScale * size.height,
        },
      });
    }
  }, [loadState, size, maxViewWidth]);
  useInterval(
    () => {
      if (
        refs.viewport.current &&
        (!maxViewWidth || refs.viewport.current.clientWidth !== maxViewWidth)
      ) {
        setMaxViewWidth(refs.viewport.current.clientWidth);
      }
    },
    100,
    true,
    [maxViewWidth]
  );
  const zoomedSize = React.useMemo(() => {
    if (!size) {
      return;
    }
    return {
      width: state.zoom * size.width,
      height: state.zoom * size.height,
    };
  }, [state.zoom]);
  const viewportSize = React.useMemo(() => {
    if (!zoomedSize) {
      return;
    }
    return {
      width: Math.min(maxViewWidth, zoomedSize.width),
      height: Math.min(maxViewHeight, zoomedSize.height),
    };
  }, [maxViewWidth, maxViewHeight, zoomedSize]);
  const onMapClick = useMediaEvent(
    (point) => {
      setFocus();
      if (!zoomedSize || !viewportSize) {
        throw "Failed to process minimap position.";
      }
      const margin = {
        x: viewportSize.width / zoomedSize.width / 2,
        y: viewportSize.height / zoomedSize.height / 2,
      };
      setState({
        ...state,
        pos: {
          x: Math.max(point.x - margin.x, 0),
          y: Math.max(point.y - margin.y, 0),
        },
      });
    },
    refs.minimap,
    [setFocus, state, viewportSize, zoomedSize]
  );
  const onImageScroll = React.useCallback(
    (event: {
      deltaX: number;
      deltaY: number;
      ctrlKey: boolean;
      preventDefault?: () => void;
      stopPropagation?: () => void;
      cursor?: Point;
    }) => {
      if (!size) return;
      event.preventDefault ? event.preventDefault() : null;
      event.stopPropagation ? event.stopPropagation() : null;
      if (!event.ctrlKey) {
        setState({
          ...state,
          pos: {
            x: Math.max(
              state.pos.x + event.deltaX / (size.width * state.zoom),
              0
            ),
            y: Math.max(
              state.pos.y + event.deltaY / (size.height * state.zoom),
              0
            ),
          },
        });
      } else {
        const center = event.cursor || cursor;
        const newZoom = Math.max(
          state.zoom - event.deltaY / (2 * 100),
          10 / Math.min(size.width, size.height)
        );
        let newPos: Point;
        if (center) {
          newPos = {
            x: Math.max(
              center.x - (state.zoom * (center.x - state.pos.x)) / newZoom,
              0
            ),
            y: Math.max(
              center.y - (state.zoom * (center.y - state.pos.y)) / newZoom,
              0
            ),
          };
        } else {
          newPos = state.pos;
        }
        setState({
          ...state,
          zoom: newZoom,
          pos: newPos,
        });
      }
      setFocus();
      return false;
    },
    [state, cursor, size]
  );
  const bind = useGesture(
    {
      onDrag: ({ delta: [deltaX, deltaY] }) => {
        if (deltaX !== 0 || deltaY !== 0) {
          onImageScroll({
            deltaX: -deltaX,
            deltaY: -deltaY,
            ctrlKey: false,
          });
          setDragging(true);
        }
      },
      onDragEnd: () => setTimeout(() => setDragging(false), 250),
      onPinch: (event) => {
        if (event.memo && event.memo > 0 && zoomedSize) {
          const cursor = convertCoordinates(
            {
              x: event.origin[0] + window.scrollX,
              y: event.origin[1] + window.scrollY,
            },
            refs.media.current
          );
          onImageScroll({
            deltaX: 0,
            deltaY: event.memo - event.da[0],
            ctrlKey: true,
            cursor,
          });
        }
        return event.last ? -1 : event.da[0];
      },
    },
    {
      drag: {
        preventDefault: true,
      },
    }
  );
  // Do this instead of onWheel in order to
  // make it non-passive.
  React.useEffect(() => {
    if (!refs.media.current) return;
    refs.media.current.addEventListener("wheel", onImageScroll, {
      passive: false,
    });
    return () => {
      if (!refs.media.current) return;
      refs.media.current.removeEventListener("wheel", onImageScroll);
    };
  }, [refs.media, onImageScroll]);
  return (
    <MediaViewerBox className="media-viewer">
      <Box sx={{ mb: 2 }}>
        <Box
          className="viewport"
          style={{
            position: "relative",
            overflow: "hidden",
            height: Math.min(
              maxViewHeight,
              zoomedSize?.height || maxViewHeight
            ),
          }}
          ref={refs.viewport}
        >
          <ClickTarget />
          {loadState == "loading" ? (
            <CircularProgress
              style={{
                position: "absolute",
                left: "50%",
                right: "50%",
                top: "50%",
                bottom: "50%",
              }}
            />
          ) : null}
          <Box
            className="media"
            ref={refs.media}
            {...bind()}
            onMouseLeave={loadState == "loaded" ? onMouseLeave : undefined}
            style={
              loadState === "loaded"
                ? ({
                    "--media-viewer-scale": state.zoom,
                    transform: `scale(${state.zoom}) translate(${pct2css(
                      -state.pos.x
                    )}, ${pct2css(-state.pos.y)})`,
                    "--media-viewer-dragging": dragging ? 1 : 0,
                    transformOrigin: "0 0",
                    position: "absolute",
                    touchAction: "none",
                  } as React.CSSProperties)
                : { width: 0, height: 0, overflow: "hidden" }
            }
          >
            {loadState === "loaded" ? children : null}
            {media.main}
          </Box>
        </Box>
        {controls || null}
      </Box>
      <Box
        className="controls"
        style={{
          display: "grid",
          gridTemplateColumns: `${state.minimapSize.width}px 1fr`,
          gridTemplateRows: "auto",
          gridTemplateAreas: '"minimap zoom"',
          gridColumnGap: 10,
        }}
      >
        <Paper
          className="minimap"
          style={{
            ...state.minimapSize,
            position: "relative",
          }}
          onClick={onMapClick}
        >
          {loadState === "loaded" && size ? (
            <div style={{ width: "100%", height: "100%" }}>
              <div
                style={{
                  transform: `scale(${state.minimapSize.width / size.width})`,
                  transformOrigin: "0 0",
                }}
              >
                {media.mini}
              </div>
              {children}
              {viewportSize && zoomedSize ? (
                <div
                  style={{
                    outline: "2px solid red",
                    outlineOffset: "-1px",
                    position: "absolute",
                    left: pct2css(state.pos.x),
                    top: pct2css(state.pos.y),
                    width: pct2css(
                      Math.min(
                        1 - state.pos.x,
                        viewportSize.width / zoomedSize.width
                      )
                    ),
                    height: pct2css(
                      Math.min(
                        1 - state.pos.y,
                        viewportSize.height / zoomedSize.height
                      )
                    ),
                  }}
                />
              ) : null}
              <div
                ref={refs.minimap}
                className="hover-target"
                style={{
                  position: "absolute",
                  top: 0,
                  ...state.minimapSize,
                  display: "block",
                }}
              />
            </div>
          ) : null}
        </Paper>
        <RangeSlider
          name="Zoom"
          className={"zoom"}
          min={Math.min(1, Math.round(100 * state.zoom))}
          max={Math.max(500, Math.round(100 * state.zoom))}
          width={"100%"}
          value={Math.round(100 * state.zoom)}
          onValueChange={(zoom) =>
            setState({
              ...state,
              zoom: zoom / 100,
            })
          }
        />
      </Box>
    </MediaViewerBox>
  );
};

export default MediaViewer;
