// qslwidgets/src/react-image-labeler/components/RegionList.tsx
import React from "react";
import { Box, styled } from "@mui/material";
import Polygon from "./Polygon";
import AlignedBox from "./AlignedBox";
import RegionCursor from "./RegionCursor";
import Mask from "./Mask";
import { Config, DraftState, CursorData } from "./library/types";

interface RegionListProps {
  config: Config;
  draft: DraftState;
  cursor: CursorData;
  callbacks: {
    onClick: (
      event: React.MouseEvent<Element, MouseEvent>,
      ...args: unknown[]
    ) => void;
    onMouseMove: (
      event: React.MouseEvent<Element, MouseEvent>,
      ...args: unknown[]
    ) => void;
  };
}

const StyledBox = styled(Box)`
  .box-text {
    font-size: calc(10pt / var(--media-viewer-scale, 1));
    font-family: Roboto, Helvetica, Arial, sans-serif;
    transform: translate(
      calc(10px / var(--media-viewer-scale, 1)),
      calc(10px / var(--media-viewer-scale, 1))
    );
  }

  svg,
  canvas {
    z-index: 1;
  }
`;

const RegionList: React.FC<RegionListProps> = ({
  draft,
  callbacks,
  cursor,
}) => {
  return (
    <StyledBox>
      {draft.labels.masks.map((mask, index) =>
        draft.drawing.mode !== "masks" ||
        draft.drawing.active?.idx !== index ? (
          <Mask
            color={mask.readonly ? "yellow" : "blue"}
            key={index}
            bitmap={mask.map}
            style={{
              pointerEvents:
                draft.drawing.mode === "masks" ? undefined : "none",
            }}
            {...callbacks}
          />
        ) : null
      )}
      {draft.labels.polygons.map((polygon, index) =>
        draft.drawing.mode !== "polygons" ||
        draft.drawing.active?.idx !== index ? (
          <Polygon
            polygon={polygon}
            style={{
              pointerEvents:
                draft.drawing.mode === "polygons" ? undefined : "none",
            }}
            key={index}
            color={polygon.readonly ? "yellow" : "blue"}
            {...callbacks}
            onClick={(event: React.MouseEvent) =>
              callbacks.onClick(event, polygon, index)
            }
          />
        ) : null
      )}
      {draft.labels.boxes.map((box, index) =>
        draft.drawing.mode !== "boxes" ||
        draft.drawing.active?.idx !== index ? (
          <AlignedBox
            color={box.readonly ? "yellow" : "blue"}
            box={box}
            key={index}
            style={{
              pointerEvents:
                draft.drawing.mode === "boxes" ? undefined : "none",
            }}
            {...callbacks}
            onClick={(event: React.MouseEvent) =>
              callbacks.onClick(event, box, index)
            }
          />
        ) : null
      )}
      {!draft.drawing.active ? null : draft.drawing.mode === "polygons" ? (
        <Polygon
          color="red"
          polygon={draft.drawing.active.region}
          {...callbacks}
          candidate={draft.drawing.active.idx > -1 ? undefined : cursor.coords}
          style={{ pointerEvents: "none" }}
        />
      ) : draft.drawing.mode === "boxes" ? (
        <AlignedBox
          color="red"
          box={draft.drawing.active.region}
          candidate={draft.drawing.active.idx > -1 ? undefined : cursor.coords}
          style={{ pointerEvents: "none" }}
          {...callbacks}
        />
      ) : draft.drawing.mode === "masks" ? (
        <Mask
          color="red"
          {...callbacks}
          bitmap={draft.drawing.active.region.map}
          style={{ pointerEvents: "none" }}
        />
      ) : null}
      {cursor.coords && draft.drawing.mode === "masks" ? (
        <RegionCursor
          x={cursor.coords.x}
          y={cursor.coords.y}
          radius={draft.drawing.radius}
        />
      ) : null}
    </StyledBox>
  );
};

export default RegionList;

// qslwidgets/src/react-image-labeler/components/RegionList.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { DraftState, Point } from "./library/types";
  import RegionBox from "./RegionBox.svelte";
  import RegionMask from "./RegionMask.svelte";
  import RegionPolygon from "./RegionPolygon.svelte";
  import RegionCursor from "./RegionCursor.svelte";
  export let draft: DraftState,
    cursor: Point | undefined = undefined;
  const dispatcher = createEventDispatcher();
  const onMouseMove = (event: MouseEvent) => dispatcher("mouseMove", { event });
  const createOnClick = (index: number) => (event: MouseEvent) => {
    dispatcher("click", {
      event,
      index,
    });
  };
</script>

<div
  class="inactive-regions {draft.drawing.mode}-mode {draft.drawing.active
    ? 'drawing-active'
    : ''}"
>
  {#each draft.labels.masks as region}
    <RegionMask
      color={region.readonly ? "yellow" : "blue"}
      bitmap={region.map}
    />
  {/each}
  {#each draft.labels.polygons as region, index}
    <RegionPolygon
      color={region.readonly ? "yellow" : "blue"}
      polygon={region}
      on:click={createOnClick(index)}
      on:mousemove={onMouseMove}
    />
  {/each}
  {#each draft.labels.boxes as region, index}
    <RegionBox
      color={region.readonly ? "yellow" : "blue"}
      box={region}
      on:click={createOnClick(index)}
      on:mousemove={onMouseMove}
    />
  {/each}
</div>
<div class="active-region">
  {#if !draft.drawing.active}
    <div />
  {:else if draft.drawing.mode === "polygons"}
    <RegionPolygon
      color="red"
      polygon={draft.drawing.active.region}
      candidate={draft.drawing.active.editable ? cursor : undefined}
    />
  {:else if draft.drawing.mode === "boxes"}
    <RegionBox
      color={"red"}
      box={draft.drawing.active.region}
      candidate={draft.drawing.active.editable ? cursor : undefined}
    />
  {:else if draft.drawing.mode === "masks"}
    <RegionMask color={"red"} bitmap={draft.drawing.active.region.map} />
  {/if}
</div>
{#if draft.drawing.mode === "masks" && cursor}
  <RegionCursor radius={draft.drawing.radius} x={cursor.x} y={cursor.y} />
{/if}

<style>
  :global(.region) {
    position: absolute;
    overflow: visible;
    z-index: 1;
  }

  :global(.region rect),
  :global(.region line) {
    stroke-width: calc(2px / var(--media-viewer-scale, 1));
  }

  :global(.region text) {
    font-size: calc(10pt / var(--media-viewer-scale, 1));
    font-family: Roboto, Helvetica, Arial, sans-serif;
    transform: translate(
      calc(10px / var(--media-viewer-scale, 1)),
      calc(10px / var(--media-viewer-scale, 1))
    );
  }

  .active-region :global(.region),
  .inactive-regions.boxes-mode :global(.polygon),
  .inactive-regions.masks-mode :global(.polygon),
  .inactive-regions.polygons-mode :global(.box),
  .inactive-regions.masks-mode :global(.box),
  :global(.region.mask),
  .inactive-regions.drawing-active :global(.region) {
    pointer-events: none;
  }
</style>
