// qslwidgets/src/react-image-labeler/ImageLabeler.tsx
import React from "react";
import { Box } from "@mui/material";

import MediaViewer from "./components/MediaViewer";
import ControlMenu from "./components/ControlMenu";
import ImagePreloader from "./components/ImagePreloader";
import RegionList from "./components/RegionList";
import EnhancementControls from "./components/EnhancementControls";
import LabelerLayout from "./components/LabelerLayout";
import {
  useLoader,
  useDraftLabelState,
  useMediaMouseCallbacks,
  useImageEnhancements,
  useCursorStyle,
} from "./components/library/hooks";
import { draft2labels } from "./components/library/utils";
import { Dimensions, ImageLabelerProps } from "./components/library/types";

const ImageLabeler: React.FC<ImageLabelerProps> = ({
  target,
  labels = { image: {} },
  options,
  callbacks,
  metadata,
  preload,
  config = { image: [], regions: [] },
}) => {
  const { draft, setDraft, resetDraft, cursor, setCursor, undo } =
    useDraftLabelState(labels, [target], [target]);
  const refs = {
    viewer: React.useRef<HTMLDivElement>(null),
    source: React.useRef<HTMLImageElement>(null),
    canvas: React.useRef<HTMLCanvasElement>(null),
  };
  const enhancements = useImageEnhancements();
  const loader = useLoader<{
    size: Dimensions;
    layout: "horizontal" | "vertical";
  }>(
    React.useCallback(
      (event: React.SyntheticEvent<HTMLImageElement, Event>) =>
        new Promise((resolve, reject) => {
          if (!refs.source.current) {
            reject("Did not find source ref.");
          } else {
            const size = {
              width: refs.source.current.naturalWidth,
              height: refs.source.current.naturalHeight,
            };
            resolve({
              size,
              layout: size.height > size.width ? "horizontal" : "vertical",
            });
          }
        }),
      [refs.source, target]
    ),
    target
  );

  const save = React.useCallback(
    () =>
      callbacks?.onSave
        ? callbacks.onSave({
            ...draft2labels(draft.labels),
            dimensions: loader.mediaState?.size,
          })
        : undefined,
    [draft, loader.mediaState, callbacks?.onSave]
  );
  const imageCallbacks = useMediaMouseCallbacks(
    draft,
    setDraft,
    setCursor,
    refs,
    config.regions && config.regions.length > 0 ? true : false,
    options?.maxCanvasSize
  );
  const cursorStyle = useCursorStyle(draft.drawing, config);
  return (
    <LabelerLayout
      metadata={metadata}
      progress={options?.progress}
      layout={loader.mediaState?.layout || "horizontal"}
      control={
        <ControlMenu
          config={config}
          disabled={loader.loadState === "loading"}
          direction={
            (loader.mediaState?.layout || "horizontal") === "horizontal"
              ? "column"
              : "row"
          }
          draft={draft}
          showNavigation={options?.showNavigation}
          setDraft={setDraft}
          callbacks={{
            ...callbacks,
            onSave: callbacks?.onSave ? save : undefined,
            onReset: resetDraft,
            onUndo: undo,
          }}
        />
      }
      content={
        <Box>
          <Box>
            <MediaViewer
              size={loader.mediaState?.size}
              cursor={cursorStyle}
              controls={
                <EnhancementControls
                  enhancements={enhancements.value}
                  setEnhancements={(update) => {
                    enhancements.set(update);
                    setDraft({ ...draft, canvas: null });
                  }}
                />
              }
              media={{
                main: target ? (
                  <img
                    {...imageCallbacks}
                    ref={refs.source}
                    onLoad={loader.callbacks.onLoad}
                    onError={loader.callbacks.onError}
                    draggable={false}
                    src={loader.src}
                    style={{
                      filter: enhancements.filter,
                    }}
                  />
                ) : null,
                mini: target ? (
                  <img
                    src={loader.src}
                    style={{
                      filter: enhancements.filter,
                    }}
                  />
                ) : null,
              }}
              loadState={loader.loadState}
              onMouseLeave={() => setCursor(undefined)}
            >
              <RegionList
                cursor={cursor}
                config={config}
                draft={draft}
                callbacks={imageCallbacks}
              />
            </MediaViewer>
          </Box>
          {loader.loadState !== "loading" && draft.canvas === null ? (
            <canvas style={{ display: "none" }} ref={refs.canvas} />
          ) : null}
          {loader.loadState !== "loading" && preload ? (
            <ImagePreloader images={preload} />
          ) : null}
        </Box>
      }
    />
  );
};

export default ImageLabeler;

// qslwidgets/src/components/ImageLabeler.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type {
    Config,
    Labels,
    Point,
    WidgetActions,
    ArbitraryMetadata,
  } from "../library/types";
  import { enhancements } from "../library/stores";
  import { createContentLoader, createDraftStore } from "../library/common";
  import LabelerLayout from "./LabelerLayout.svelte";
  import ControlMenu from "./ControlMenu.svelte";
  import MediaViewer from "./MediaViewer.svelte";
  import RegionList from "./RegionList.svelte";
  import Metadata from "./Metadata.svelte";
  export let target: string | undefined,
    config: Config,
    labels: Labels,
    metadata: ArbitraryMetadata = {},
    navigation: boolean = false,
    editableConfig: boolean = false,
    maxCanvasSize: number = 512,
    transitioning: boolean = false,
    viewHeight: number = 384,
    actions: WidgetActions = {};
  const dispatcher = createEventDispatcher();
  let image: HTMLImageElement;
  let cursor: Point | undefined = undefined;
  let { draft, history } = createDraftStore();
  const invalidateImage = () => {
    if ($draft.image) {
      $draft.image.free();
      draft.set({ ...$draft, image: null });
    }
  };
  // If our enhancements change.
  $: $enhancements, invalidateImage();
  $: target, labels, draft.reset(labels);
  $: ({ callbacks: loadCallbacks, state: loadState } = createContentLoader({
    target,
    load: async (event: { currentTarget: HTMLElement }) => {
      const target = event.currentTarget as HTMLImageElement;
      return {
        size: {
          width: target.naturalWidth,
          height: target.naturalHeight,
        },
      };
    },
  }));
  let layout: "horizontal" | "vertical" = "vertical";
  $: if ($loadState.mediaState)
    layout =
      $loadState.mediaState.size.width > $loadState.mediaState.size.height
        ? "vertical"
        : "horizontal";
</script>

<LabelerLayout {layout}>
  <svelte:fragment slot="content">
    <MediaViewer
      size={$loadState.mediaState?.size}
      {viewHeight}
      loadState={transitioning ? "loading" : $loadState.loadState}
    >
      <img
        slot="main"
        src={target}
        alt="labeling target image: {target}"
        on:load={loadCallbacks.load}
        on:error={loadCallbacks.error}
        bind:this={image}
      />
      <img slot="mini" src={target} alt="minimap for {target}" />
      <RegionList
        slot="regions"
        target={image}
        on:change={draft.snapshot}
        {maxCanvasSize}
        bind:image={$draft.image}
        bind:drawing={$draft.drawing}
        bind:labels={$draft.labels}
        bind:cursor
      />
    </MediaViewer>
    <Metadata {metadata} />
  </svelte:fragment>
  <svelte:fragment slot="control">
    <ControlMenu
      bind:config
      bind:draft={$draft}
      on:change={draft.snapshot}
      on:next
      on:prev
      on:delete
      on:ignore
      on:unignore
      on:showIndex
      on:undo={() => history.undo()}
      {layout}
      on:save={() => {
        labels = draft.export($loadState.mediaState?.size);
        dispatcher("save");
      }}
      on:reset={() => draft.reset(labels)}
      disabled={transitioning || $loadState.loadState === "loading"}
      {editableConfig}
      {navigation}
      actions={{ ...actions, undo: $history > 0 }}
    />
  </svelte:fragment>
</LabelerLayout>
