// qslwidgets/src/react-image-labeler/components/Metadata.tsx
import React from "react";
import {
  TableBody,
  TableContainer,
  Table,
  Paper,
  TableRow,
  TableCell,
} from "@mui/material";

type MetadataProps = {
  data: { [key: string]: string };
};

const Metadata: React.FC<MetadataProps> = ({ data }) => {
  return (
    <TableContainer tabIndex={0} component={Paper} sx={{ mb: 0, mt: 0 }}>
      <Table aria-label="metadata table">
        <TableBody>
          {Object.entries(data).map(([key, value], idx) => (
            <TableRow
              key={idx}
              sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
            >
              <TableCell align="right" component="th" scope="row">
                <b>{key}</b>
              </TableCell>
              <TableCell>{value}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};
export default Metadata;

// qslwidgets/src/components/Metadata.svelte
<script lang="ts">
  import type { ArbitraryMetadata } from "../library/types";
  export let metadata: ArbitraryMetadata | undefined = {};
</script>

{#if metadata && Object.keys(metadata).length > 0}
  <table tabindex="0" class="metadata">
    {#each Object.entries(metadata) as [key, value]}
      <tr>
        <td>{key}</td>
        <td>{value}</td>
      </tr>
    {/each}
  </table>
{/if}

<style>
  table {
    width: 100%;
    border: 1px solid;
    border-color: var(--border-color);
  }
  td {
    padding: 10px;
  }
  td:first-of-type {
    text-align: right;
    font-weight: bold;
  }
  td:last-of-type {
    text-align: left;
  }
</style>
