// qslwidgets/src/react-image-labeler/components/RegionCursor.tsx
import React from "react";
import { pct2css } from "./library/utils";

const BORDER_THICKNESS = 2;

const RegionCursor: React.FC<{
  radius: number;
  x: number;
  y: number;
}> = ({ radius, x, y }) => {
  return (
    <div
      className="mask-cursor"
      style={{
        height: `${radius * 2}px`,
        width: `${radius * 2}px`,
        boxSizing: "content-box",
        transform: `translate(${-radius - BORDER_THICKNESS}px, ${
          -radius - BORDER_THICKNESS
        }px) scale(calc(1/var(--media-viewer-scale, 1)))`,
        left: pct2css(x),
        top: pct2css(y),
        position: "absolute",
        border: `${BORDER_THICKNESS}px solid red`,
        cursor: "none",
        overflow: "visible",
        pointerEvents: "none",
        zIndex: 1,
      }}
    />
  );
};

export default RegionCursor;

// qslwidgets/src/components/RegionCursor.svelte
<script lang="ts">
  import { pct2css } from "../library/common";
  const borderThickness = 2;
  export let x: number, y: number, radius: number;
</script>

<div
  class="mask-cursor"
  style="
    height: {radius * 2}px;
    width: {radius * 2}px;
    border: {borderThickness}px solid red;
    transform: translate({-radius - borderThickness}px, {-radius -
    borderThickness}px) scale(calc(1/var(--media-viewer-scale, 1)));
    left: {pct2css(x)};
    top: {pct2css(y)};
  "
/>

<style>
  div {
    position: absolute;
    box-sizing: content-box;
    cursor: none;
    overflow: visible;
    pointer-events: none;
    z-index: 1;
  }
</style>
