// qslwidgets/src/react-image-labeler/TimeSeriesLabeler.tsx
import React from "react";
import FileSaver from "file-saver";
import MediaViewer from "./components/MediaViewer";
import TimeSeries from "./components/TimeSeries";
import ControlMenu from "./components/ControlMenu";
import LabelerLayout from "./components/LabelerLayout";
import { Box, styled } from "@mui/material";
import { draft2labels } from "./components/library/utils";
import { useDraftLabelState, useMediaEvent } from "./components/library/hooks";
import { processSelectionChange } from "./components/library/handlers";
import { TimeSeriesLabelerProps } from "./components/library/types";
import html2canvas from "html2canvas";
import Metadata from "./components/Metadata";
import GlobalLabelerContext from "./components/GlobalLabelerContext";

const DownloadContainer = styled(Box)`
  & .metadata table {
    border: 1px solid;
  }
  & .metadata {
    margin-top: 5px;
    box-shadow: none;
    border-radius: 0;
  }
`;

const TimeSeriesLabeler: React.FC<TimeSeriesLabelerProps> = ({
  target,
  labels,
  config = { image: [] },
  options,
  callbacks,
  metadata,
}) => {
  const refs = {
    container: React.useRef<HTMLDivElement>(null),
    downloadable: React.useRef<HTMLDivElement>(null),
  };
  const { setToast } = React.useContext(GlobalLabelerContext);
  const { draft, setDraft, resetDraft, cursor, setCursor, undo } =
    useDraftLabelState(labels, [target], [target]);
  const onMouseMove = useMediaEvent(
    (coords) => {
      setCursor({ ...cursor, coords });
    },
    refs.container,
    [cursor]
  );
  const onMouseLeave = React.useCallback(
    () => setCursor({ ...cursor, coords: undefined }),
    [cursor]
  );
  const save = React.useCallback(
    () =>
      callbacks?.onSave
        ? callbacks.onSave({
            ...draft2labels(draft.labels),
          })
        : undefined,
    [draft, callbacks?.onSave]
  );
  const toggle = React.useCallback(
    (label, value) =>
      setDraft({
        ...draft,
        dirty: true,
        labels: {
          ...draft.labels,
          image: {
            ...draft.labels.image,
            [label]: processSelectionChange(
              value,
              draft.labels.image[label] || [],
              config.image
                ? config.image.filter((c) => c.name === label)[0]?.multiple
                : false
            ),
          },
        },
      }),
    [draft.labels, config, setDraft]
  );
  const size = React.useMemo(
    () =>
      target
        ? target.plots.reduce(
            (memo, current) => {
              return {
                width: memo.width + (current.size?.width || 512),
                height: memo.height + (current.size?.height || 256),
              };
            },
            { width: 0, height: 0 }
          )
        : undefined,
    [target]
  );
  const onDownload = React.useCallback(async () => {
    await html2canvas(refs.downloadable.current as HTMLElement, {
      logging: false,
    }).then((canvas) => {
      if (!target?.filename) {
        return;
      }
      const png = canvas.toDataURL("image/png", 1.0);
      if (png) {
        FileSaver.saveAs(
          png,
          target.filename.toLowerCase().endsWith(".png")
            ? target.filename
            : target.filename + ".png"
        );
      } else {
        setToast("Failed to render figure.");
      }
    });
  }, [target, labels, refs.downloadable, setToast]);
  return (
    <Box>
      <LabelerLayout
        metadata={metadata}
        progress={options?.progress}
        layout={"vertical"}
        control={
          <ControlMenu
            cursor={cursor}
            config={{ image: config.image || [] }}
            setCursor={setCursor}
            allowRegion={false}
            disabled={false}
            direction={"row"}
            draft={draft}
            showNavigation={options?.showNavigation}
            setDraft={setDraft}
            callbacks={{
              ...callbacks,
              onSave: callbacks?.onSave ? save : undefined,
              onReset: resetDraft,
              onDownload: target?.filename ? onDownload : undefined,
              onUndo: undo,
            }}
          />
        }
        content={
          <MediaViewer
            cursor={cursor.coords}
            onMouseLeave={onMouseLeave}
            media={{
              main: target ? (
                <Box ref={refs.container} onMouseMove={onMouseMove}>
                  <TimeSeries
                    target={target}
                    labels={draft.labels}
                    toggle={toggle}
                  />
                </Box>
              ) : undefined,
              mini: target ? (
                <TimeSeries target={target} labels={draft.labels} />
              ) : undefined,
            }}
            size={size}
            loadState={"loaded"}
          />
        }
      />
      {target && size ? (
        <Box style={{ overflow: "scroll", height: 0 }}>
          <DownloadContainer
            ref={refs.downloadable}
            style={{ display: "inline-block", padding: 20 }}
          >
            <TimeSeries target={target} labels={draft.labels} />
            {metadata ? <Metadata data={metadata} /> : null}
          </DownloadContainer>
        </Box>
      ) : undefined}
    </Box>
  );
};

export default TimeSeriesLabeler;

// qslwidgets/src/components/TimeSeriesLabeler.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type {
    Config,
    Labels,
    WidgetActions,
    Dimensions,
    ArbitraryMetadata,
    TimeSeriesTarget,
  } from "./library/types";
  import html2canvas from "html2canvas";
  import FileSaver from "file-saver";
  import { createDraftStore } from "./library/common";
  import { toast } from "./library/stores";
  import ControlMenu from "./ControlMenu.svelte";
  import MediaViewer from "./MediaViewer.svelte";
  import TimeSeries from "./TimeSeries.svelte";
  import Metadata from "./Metadata.svelte";
  export let target: TimeSeriesTarget | undefined,
    config: Config,
    labels: Labels,
    metadata: ArbitraryMetadata = {},
    navigation: boolean = false,
    editableConfig: boolean = false,
    transitioning: boolean = false,
    actions: WidgetActions = {};
  const dispatcher = createEventDispatcher();
  let { draft, history } = createDraftStore();
  $: target, labels, draft.reset(labels);
  let downloadContainer: HTMLDivElement;
  let chartSize: Dimensions | undefined = undefined;
  const download = () => {
    html2canvas(downloadContainer, {
      logging: false,
    }).then((canvas) => {
      if (!target?.filename) {
        return;
      }
      const png = canvas.toDataURL("image/png", 1.0);
      if (png) {
        FileSaver.saveAs(
          png,
          target.filename.toLowerCase().endsWith(".png")
            ? target.filename
            : target.filename + ".png"
        );
      } else {
        toast.push("Failed to render figure.");
      }
    });
  };
</script>

<MediaViewer
  size={chartSize}
  loadState={transitioning ? "loading" : "loaded"}
  enhancementControls={false}
>
  <svelte:fragment slot="main"
    ><TimeSeries
      {config}
      {target}
      bind:labels={$draft.labels}
      bind:chartSize
    /></svelte:fragment
  >
  <svelte:fragment slot="mini"
    ><TimeSeries {config} {target} labels={$draft.labels} /></svelte:fragment
  >
</MediaViewer>
<Metadata {metadata} />
<ControlMenu
  bind:config
  bind:draft={$draft}
  on:change={draft.snapshot}
  on:next
  on:prev
  on:delete
  on:ignore
  on:unignore
  on:showIndex
  on:download={download}
  on:undo={() => history.undo()}
  on:save={() => {
    labels = draft.export();
    dispatcher("save");
  }}
  on:reset={() => draft.reset(labels)}
  disabled={transitioning}
  {editableConfig}
  {navigation}
  regions={false}
  actions={{ ...actions, undo: $history > 0, download: !!target?.filename }}
/>
<div class="download-container-wrapper">
  <div bind:this={downloadContainer} class="download-container">
    <TimeSeries {config} {target} labels={$draft.labels} />
    <Metadata {metadata} />
  </div>
</div>

<style>
  .download-container {
    --text-color: black;
    display: inline-block;
    padding: 20;
  }
  .download-container-wrapper {
    height: 0;
    overflow: scroll;
  }
</style>
